from typing import Any, Callable, Dict, overload, Literal
from logging import Logger

def profile(on: bool=True, save:bool=False, output_unit:float|None=None) -> Callable: ...

class Timer:
    def __init__(self, *str_or_funcs, output_unit: float|None = None, save=False): ...

def print_memory_usage(obj: Any) -> None: ...
def clear(name: Any) -> None: ...
def get_free_space(folder: str) -> float: ...
def create_folder(path1: str, path2: None | str = None) -> str: ...
def save_hdf5(filename: str, group: str, data: dict[str, Any], mode: str = 'a') -> tuple[str, str]: ...
def load_hdf5(filename: str, group: str, dataname: str) -> Any: ...
def isave(filename:str, *data, dataset:dict|None = None, group: str|None = "/", mode:str='a') -> None: ...
@overload
def iload(filename: str, dataset: None|str = None, group: str|None = None) -> Any: ...
@overload
def iload(filename: str, dataset: list[str], group: str|None = None) -> list: ...
def view_hdf5(filename: str, group: str, depth: int = 1): ...
def set_logging(level:Literal[-1,1,2,3,4]=1, savelog: bool = False, filenameTime: bool = False, logtime: bool = False) -> None: ...
def println(*inputargs, level:int=1) -> None: ...
def show(*inputargs, level:int=1) -> None: ...
def set_show(use_color=None, arg_name=None) -> None: ...

_SAVE_FUC: Dict[str, Callable]
_LOAD_FUC: Dict[str, Callable]
logger: Logger


def plt_style_use(stylename:str = "quante", svg: bool = True) -> None: ...