import numpy as _np
from _typeshed import Incomplete

__all__ = ['entanglement_spectrum', 'entropy', 'entropy_page', 'cg_coef', 'mean_level_spacing', 'plot_energy_density', 'plot_energy_hist', 'plot_level_spacing_distribution']

def entanglement_spectrum(state:_np.ndarray, L:int, left_number:int, basis=None) -> _np.ndarray: ...
def entanglement_entropy(state:_np.ndarray, L:int, left_number:int, basis=None) -> float: ...
def entropy(a, rank: Incomplete | None = None, base=...) -> _np.float64: ...
def entropy_page(Dim_sub: int, Dim_tot: int) -> _np.float64: ...
def cg_coef(j1: int, j2: int, j3: int, m1: int, m2: int, m3: int) -> float: ...
def mean_level_spacing(E, verbose: bool = True): ...
def plot_energy_density(vals, ax: Incomplete | None = None, bandwidth: float = 1.0): ...
def plot_energy_hist(vals, ax: Incomplete | None = None, bins: Incomplete | None = None): ...
def plot_level_spacing_distribution(eps, ax: Incomplete | None = None, bins: Incomplete | None = None, beta: int = 1) -> None: ...
