import numpy as _np
import scipy.sparse as sps
from _typeshed import Incomplete
from typing import TYPE_CHECKING, overload
if TYPE_CHECKING:
    import torch

__all__ = [
    "spectral_form_factor",
    "entanglement_spectrum",
    "entanglement_entropy",
    "entropy",
    "entropy_page",
    "cg_coef",
    "unfolding",
    "mean_level_spacing",
]

__all__ += [
    "plot_energy_density", 
    "plot_energy_hist", 
    "plot_level_spacing_distribution", 
]

__all__ += [
    "Ginibre_distribution",
    "Poisson_distribution",
    "WignerDyson_distribution",
]

def spectral_form_factor(engs:_np.ndarray, times:_np.ndarray | float): ...
def entanglement_spectrum(state:_np.ndarray, left_number:int, basis=None) -> _np.ndarray: ...
def entanglement_entropy(state:_np.ndarray, left_number:int, basis=None) -> float | _np.ndarray: ...
def entropy(a, rank: Incomplete | None = None, base=...) -> _np.float64: ...
def entropy_page(Dim_sub: int, Dim_tot: int) -> _np.float64: ...
def cg_coef(j1: int, j2: int, j3: int, m1: int, m2: int, m3: int) -> float: ...
def unfolding(eng, discard=0.2, polynomial_of_degree=15, n=30): ...
def mean_level_spacing(E, verbose: bool = True): ...
def plot_energy_density(vals, ax: Incomplete | None = None, bandwidth: float = 1.0): ...
def plot_energy_hist(vals, ax: Incomplete | None = None, bins: Incomplete | None = None): ...
def plot_level_spacing_distribution(eps, ax: Incomplete | None = None, bins: Incomplete | None = None, beta: int = 1) -> None: ...
def Ginibre_distribution(s, M=100): ...
def Poisson_distribution(s, complex_plane=False): ...
def WignerDyson_distribution(s, beta=1): ...