import torch as tc
from ...linalg.svd_robust import TruncationError
from _typeshed import Incomplete
from numbers import Number
from typing import Optional, Generator, Any, Union, TypeVar, Literal

T = TypeVar('T', bound='TensorTrain')

__all__ = ['MPS', 'MPO', 'ProjMPO']

class TensorTrain:
    data: list[tc.Tensor]
    length: int
    Ss: list[Optional[tc.Tensor]]
    llim: Optional[int]
    rlim: Optional[int]
    lognm: tc.Tensor
    dtype: tc.dtype
    device: tc.device
    def __init__(self, Ws: list[tc.Tensor], Ss: list[tc.Tensor] = None, llim: int = None, rlim: int = None, lognm: float = None) -> None: ...
    def add_(self, anotherTT) -> None: ...
    def copy(self:T)->T: ...
    def __add__(self, anotherTT): ...
    def sub_(self, anotherTT) -> None: ...
    def __sub__(self, antoherTT): ...
    def __rmul__(self, number: tc.Tensor): ...
    def maxbonddim(self) -> int: ...
    def bonddims(self) -> list[int]: ...
    def to(self, dtype: Incomplete | None = None, device:Optional[Literal["cpu", "cuda"]]=None) -> None: ...
    def save(self, path: str) -> None: ...
    @classmethod
    def loadpth(cls, path) -> Union[MPO,MPS]: ...
    def to_matrix(self) -> tc.Tensor: ...
    def inner(self, anotherMPS, logscale: bool = False, conj: bool = False) -> tc.Tensor: ...
    def norm(self, lognorm: bool = False) -> tc.Tensor: ...
    def normalize_(self) -> None: ...
    def entanglement_entropy(self, bonds: int) -> tc.Tensor: ...
    def move_llim_(self, j) -> None: ...
    def move_rlim_(self, j) -> None: ...
    def is_orthogonal_form(self) -> bool: ...
    def is_canonical_form(self) -> bool: ...
    def check_canonical_form(self) -> None: ...
    def check_orthogonal_form(self) -> None: ...
    def orthogonalize_(self, j: int, normalize: bool = True) -> None: ...
    def canonicalize_(self, trunc_para: tuple[int, float, float] = (None, None, None), qrnormalize: bool = False) -> None: ...
    def apply_gate_(self, pos: int, gate: tc.Tensor | tuple[tc.Tensor, str], *, direction: str = None, svd_alg: str = 'eig', trunc_para: tuple[int, float, float] = (None, None, None), updateS: bool = False, normalize: bool = False, gate_range: Literal[1,2] = 2, unitary_gate: bool = False) -> None: ...
    def update_single_site_(self, pos, phi, normalize: bool = False, unitary_gate: bool = False) -> None: ...
    def update_two_site_(self, pos, W, direction, *, method: str = 'eig', trunc_para: tuple[int, float, float] = (None, None, None), normalize: bool = False, pertube: Incomplete | None = None, updateS: bool = True) -> TruncationError: ...
    def update_two_site_cannonical_(self, pos, W, method: str = 'eig', trunc_para: tuple[int, float, float] = (None, None, None), normalize: bool = False) -> TruncationError: ...
    def apply_mpo_(self, Ws_mpo: MPO, trunc_para: tuple[int, float, float] = (None, None, None), dtype=..., updateS: bool = True, normalize: bool = False) -> None: ...
    def apply_mpo_naive_(self, Ws_mpo: MPO) -> None: ...

class MPS(TensorTrain):
    def __init__(self, Ws: list[tc.Tensor], Ss: list[tc.Tensor] = None, llim: int = None, rlim: int = None, lognm: float = None) -> None: ...
    @classmethod
    def random(cls, N: int, linkdims: list[int] | int, dtype=..., device:Optional[Literal["cpu", "cuda"]]=None) -> MPS: ...
    @classmethod
    def product_state(cls, state: list[str], dtype=..., device:Optional[Literal["cpu", "cuda"]]=None) -> MPS: ...
    @classmethod
    def ghz_state(cls, L, dtype=..., device:Optional[Literal["cpu", "cuda"]]=None) -> MPS: ...
    @classmethod
    def w_state(cls, L, which: str = 'up', dtype=..., device:Optional[Literal["cpu", "cuda"]]=None) -> MPS: ...
    def show(self, full: bool = False) -> None: ...
    def measure(self, operator: tc.Tensor | str, pos: int | list[int]) -> tc.Tensor: ...

class MPO(TensorTrain):
    def __init__(self, Ws: list[tc.Tensor], Ss: list[tc.Tensor] = None, llim: int = None, rlim: int = None, lognm: float = None) -> None: ...
    @classmethod
    def random(cls, N: int, linkdims: list[int] | int, phydim: int = 2, dtype=..., device:Optional[Literal["cpu", "cuda"]]=None) -> MPO: ...
    @classmethod
    def heisenberg(cls, L: int, j: int = 1, h: int = 0, cyclic: bool = False, pauli: bool = True, device:Optional[Literal["cpu", "cuda"]]=None) -> MPO: ...
    @classmethod
    def eye(cls, L: int, local_dims: int =2, dtype=tc.float64, device:Optional[Literal["cpu", "cuda"]]=None) -> MPO: ...
    @classmethod
    def from_oper(cls, ham, L, pauli: bool = True, device:Optional[Literal["cpu", "cuda"]]=None) -> MPO: ...
    def show(self, full: bool = False) -> None: ...
    def diag_inner(self, mps) -> tc.Tensor: ...
    def exp(self, x, order: int = 2, trunc_para: tuple[int, float, float] = (None, None, None), dtype=...) -> MPO: ...
    def trace(self) -> tc.Tensor: ...
    def dmrg(self, psi0: MPS, nsweep: int, chi_max: list[int], cutoff: list[float], backend: str = 'default', svd_alg: str = 'svd', nsite: int = 2, outputlevel: int = 1) -> tuple[tc.Tensor, MPS]: ...
    def tdvp(self, init: MPS, t: Number, time_step: Number, chi_max: list[int], trunc_cut: list[float], *, backend: str = 'default', svd_alg: str = 'svd', normalize: bool = True, reverse_step: bool = True, time_start: float = 0.0, nsite: int = 2, order: int = 2, outputlevel: int = 1) -> Generator[tuple[float, MPS], Any, None]: ...

class DMRG: ...
class TDVP: ...
class ProjMPO:
    lpos: int
    rpos: int
    nsite: int
    L: int
    mpo: MPO
    LR: list[Optional[tc.Tensor]]
    dtype: tc.dtype
    def __init__(self, H, nsite: int = 2) -> None: ...
    def copy(self) -> ProjMPO: ...
    def set_position_(self, psi: MPS, pos: int) -> None: ...
    def solve_ground_state(self, v, *, method: str = 'default', lanczos_tol: float = 1e-14) -> Union[tc.Tensor, tc.Tensor]: ...
    def solve_evolve_state(self, v, delta, *, method: str = 'default', lanczos_tol: float = 1e-14) -> tc.Tensor: ...
    def to_matrix(self) -> tc.Tensor: ...

class InfMPS:
    Ss: list
    data: list
    def __init__(self, data, Ss) -> None: ...
    def apply_gate_(self, gates, svd_alg="eig", trunc_para=(None,None,None), gate_range=2, unitary_gate=False) -> None: ...