from typing import Union
import numpy as np

class SpinBasis:
    L: int
    S: Union[int, float]
    Ns: int
    def __init__(self, L: int, S: int | float = 0.5) -> None: ...
    def where_codes(self, method_name: str = None) -> None: ...
    def _sparse_matrix(self, op_list, hascomplex, savememory=False): ...
    def to_full_space(self, index: int, from_Nup_space: bool = False) -> np.ndarray: ...
    def projection_matrix(self, from_Nup_space: bool = False) -> np.ndarray: ...
    @classmethod
    def print_dims(cls, L: int) -> None: ...
    def project(self, state:np.ndarray, from_Nup_space:bool = False) -> np.ndarray: ...
    def recover(self, state:np.ndarray) -> np.ndarray: ...

class SpinHalfBasis(SpinBasis):
    def __init__(self, L: int) -> None: ...

class SpinHighBasis(SpinBasis):
    def __init__(self, L: int, S:Union[float, int]) -> None: ...