import numpy as _np
import scipy.sparse as _sparse
from _typeshed import Incomplete
from typing import Optional

__all__ = ['PAULI_MAT', 'pauli_matrix', 'random_matrix', 'random_orthorgonal_matrix_close_I', 'random_unitary_matrix_close_I', 'random_sparse_matrix', 'hadamard_gate', 'phase_gate', 'rotation_gate', 'heisenberg_matrix', 'random_phase_model', 'local_hamiltonian_spin_1D']

PAULI_MAT = {
    "X": _np.array([[0.,1.],[1.,0.]]),
    "Y": _np.array([[0.,-1.j],[1.j,0.]]),
    "Z": _np.array([[1.,0.],[0.,-1.]]),
    "P": _np.array([[0.,1.],[0.,0.]]),
    "M": _np.array([[0.,0.],[1.,0.]]),
    "I": _np.array([[1.,0.],[0.,1.]]),
    "x": _np.array([[0.,0.5],[0.5,0.]]),
    "y": _np.array([[0.,-0.5j],[0.5j,0.]]),
    "z": _np.array([[0.5,0.],[0.,-0.5]]),
    "p": _np.array([[0.,1.],[0.,0.]]),
    "m": _np.array([[0.,0.],[1.,0.]]),
    "+": _np.array([[0.,1.],[0.,0.]]),
    "-": _np.array([[0.,0.],[1.,0.]]),
    "i": _np.array([[1.,0.],[0.,1.]]),
    "u": _np.array([[1.], [0.]]),
    "d": _np.array([[0.], [1.]]),
}

def pauli_matrix(stri: str, S: Union[str, float, int] = '1/2') -> _np.ndarray: ...
def random_matrix(dim, type: str = 'simple', seed: Incomplete | None = None): ...
def random_orthorgonal_matrix_close_I(dim, a=0.01, seed=None): ...
def random_unitary_matrix_close_I(dim, a: float = 0.01, seed: Incomplete | None = None): ...
def random_sparse_matrix(dim, density: float = 0.1, seed: Incomplete | None = None): ...
def parallel_build_matrix(hlocals, positions, coefficients, L, S, pauli=False, sparse=False, parallel=False, nthreads:Optional[int] =None):...
def heisenberg_matrix(L, j: float | tuple = 1.0, h: float | tuple = 0.0, pauli: bool = False, S: int | float | str = ..., cyclic: bool = False, Nup: int | None = None, kblock: int | None = None, pblock: int | None = None, zblock: int | None = None, pzblock: int | None = None, jmblock: int | tuple[int, int] | None = None): ...
def hadamard_gate(dtype=...): ...
def phase_gate(phi: float = 0.0, dtype=...): ...
def rotation_gate(phi, xyz: str = 'Z', dtype=...): ...
def random_phase_model(L, q, ε, seed: Incomplete | None = None): ...
def local_hamiltonian_spin_1D(model_key: str, pauli: bool = True, **kwargs) -> _np.ndarray: ...
def syk_matrix(L:int, J:_np.ndarray, sparse=False): ...