import numbers as _numbers
import numpy as _np
import scipy.sparse as _sp
from _typeshed import Incomplete
from typing import Callable, Generator, Union, overload, Literal, Type, Optional

from typing import TYPE_CHECKING
if TYPE_CHECKING:  # 类型检查时，导入 torch
    from ..torch_utils.tensor_network.tnclass import MPO as tcMPO
    from ..tensor import MPO as npMPO

class Oper:
    type: Incomplete
    data: Incomplete
    def __init__(self, data: dict[str, dict[tuple[int], float | complex]], type: str = 's') -> None: ...
    def copy(self) -> Oper: ...
    def __add__(self, oper: Oper | _numbers.Number, a: float = 1.0) -> Oper: ...
    def each_term(self) -> Generator[tuple[str, tuple[int], float | complex], None, None]: ...
    def __radd__(self, oper: Oper | _numbers.Number) -> Oper: ...
    def __mul__(self, scale: Oper | _numbers.Number) -> Oper: ...
    def __rmul__(self, scale) -> Oper: ...
    def __sub__(self, oper: Oper | _numbers.Number) -> Oper: ...
    def __rsub__(self, oper: Oper | _numbers.Number) -> Oper: ...
    def __neg__(self) -> Oper: ...
    def __truediv__(self, num: float | complex) -> Oper: ...
    def __matmul__(self, oper: Oper) -> Oper: ...
    def __pow__(self, n, m: Incomplete | None = None) -> Oper: ...
    def show_string_form(self) -> None: ...
    def save(self, filename:str = 'ham.h5') -> None: ...
    @classmethod
    def load(self, filename:str) -> 'Oper': ...
    def sort_posn(self) -> Oper: ...
    def expandxy(self, pauli: bool = False) -> Oper: ...
    def dtype(self) -> Type[Union[float, complex]]: ...
    def split_data(self) -> tuple[list[str], list[tuple[int]], list[int | float | complex]]: ...
    def quspin_form(self) -> list[list[list[int | float | complex]]]: ...
    @overload
    def to_matrix(self, basis, pauli: bool = False, sparse: Literal[False] = False) -> _np.ndarray: ...
    @overload
    def to_matrix(self, basis, pauli: bool = False, sparse: Literal[True] = False) -> _sp.csr_array: ...
    def automata(self, L: int, pauli: bool = False, d: int = 2, local_matrix: Callable[[str], _np.ndarray] | None = None, dtype: type[_np.complex128] = ...) -> list[_np.ndarray]: ...
    def gate2_decomposition(self, L:int, tau=0.1, form:Literal["ladder", "brick"]="ladder", pauli:bool=True) -> tuple[list[int],list[_np.ndarray]]: ...
    def trotter_gates(self, L:int, tau:float, order:Literal["1", "2", "4", "4_opt"]="2", evolve_type:Literal["time", "temporal"]="time", N_step:int=1, pauli:bool=True) -> tuple[list[int], list[_np.ndarray]]: ...
    def local(self, site_position:int, L:int, pauli:bool=True) -> _np.ndarray: ...
    @overload
    def to_mpo(self, L, pauli=False, backend: Literal["torch"]='torch', device:Optional[str]=None) -> tcMPO: ...
    @overload
    def to_mpo(self, L, pauli=False, backend: Literal["tensor"]='tensor', device:Optional[str]=None) -> npMPO: ...

def I(i: int = 0) -> Oper: ...
def p(i: int = 0) -> Oper: ...
def m(i: int = 0) -> Oper: ...
def x(i: int = 0) -> Oper: ...
def y(i: int = 0) -> Oper: ...
def z(i: int = 0) -> Oper: ...
def n(i: int = 0) -> Oper: ...
def nn(i: int, j: int) -> Oper: ...
def zz(i: int, j: int) -> Oper: ...
def mp(i: int, j: int) -> Oper: ...
def pm(i: int, j: int) -> Oper: ...
def xx(i: int, j: int) -> Oper: ...
def yy(i: int, j: int) -> Oper: ...
def xy(i: int, j: int) -> Oper: ...
def yx(i: int, j: int) -> Oper: ...
def sum(*oper) -> Oper: ...
def heisenberg_operator(L:int, j:Union[float,int,complex] = 1.0, h:Union[float,int,complex] = 0.0, cyclic: bool=False) -> Oper: ...