import numpy as _np
import scipy.sparse as _sparse
from _typeshed import Incomplete

__all__ = ['basis_state', 'xplus', 'xminus', 'plus', 'minus', 'yplus', 'yminus', 'bloch', 'bell', 'singlet', 'thermal', 'neel', 'singlet_pairs', 'ghz', 'w', 'antisymmetric', 'random']

def spin_up(dtype=float) -> _np.ndarray: ...
def spin_down(dtype=float) -> _np.ndarray: ...
def basis_state(i, dim, dtype=...): ...
def product_state(binary, dtype=..., **kwargs): ...
def neel(L: int, down_first: bool = False, dtype=..., **kwargs): ...
def ghz(L): ...
def w(L, dtype=...): ...
def random(dim: int, n: int = 1, dtype: type = ..., seed: int | None = None) -> _np.ndarray: ...
def random_sparse(dim: int, n: int = 1, density: float = 1., dtype: type = complex, seed: int | None = None) -> _sparse.sparray: ...
def bloch(theta: float, phi: float, j: int | float) -> _np.ndarray: ...
def xplus(dtype=...) -> _np.ndarray: ...
def xminus(dtype=...) -> _np.ndarray: ...
def yplus(dtype=...) -> _np.ndarray: ...
def yminus(dtype=...) -> _np.ndarray: ...
def plus(dtype=...) -> _np.ndarray: ...
def minus(dtype=...) -> _np.ndarray: ...
def bell(s, dtype=...): ...
def singlet(dtype=...): ...
def thermal(ham, beta: Incomplete | None = None, precomp_func: bool = False): ...
def singlet_pairs(n, **kwargs): ...
def antisymmetric(*args): ...
