import numpy as _np
import scipy.sparse as _sp
from _typeshed import Incomplete
from typing import Callable, Generator, Union, overload, Literal, Type, Optional, Iterable

from typing import TYPE_CHECKING
if TYPE_CHECKING:  # 类型检查时，导入 torch
    from ...torch_utils.networks import MPO as tcMPO
    from quimb.tensor.tensor_1d import MatrixProductOperator as quMPO

number = Union[int,float,complex]

class Oper:
    type: Incomplete
    data: Incomplete
    def __init__(self, data: dict[str, dict[tuple[int], float | complex]], type: str = 's') -> None: ...
    def copy(self) -> Oper: ...
    def __add__(self, oper: Oper | number, a: float = 1.0) -> Oper: ...
    def each_term(self) -> Generator[tuple[str, tuple[int], float | complex], None, None]: ...
    def __radd__(self, oper: Oper | number) -> Oper: ...
    def __mul__(self, scale: Oper | number) -> Oper: ...
    def __rmul__(self, scale) -> Oper: ...
    def __sub__(self, oper: Oper | number) -> Oper: ...
    def __rsub__(self, oper: Oper | number) -> Oper: ...
    def __neg__(self) -> Oper: ...
    def __truediv__(self, num: float | complex) -> Oper: ...
    def __matmul__(self, oper: Oper) -> Oper: ...
    def __pow__(self, n, m: Incomplete | None = None) -> Oper: ...
    def show_string_form(self) -> None: ...
    def save(self, filename:str = 'ham.h5') -> None: ...
    @classmethod
    def load(cls, filename:str) -> 'Oper': ...
    def trotter_gates(self,) -> tuple[list[int], list[_np.ndarray]]: ...


class SpinOper:
    type: Incomplete
    data: Incomplete
    def __init__(self, data: dict[str, dict[tuple[int], float | complex]], type: str = 's') -> None: ...
    def copy(self) -> SpinOper: ...
    def __add__(self, oper: SpinOper | number, a: float = 1.0) -> SpinOper: ...
    @property
    def L(self): ...
    def each_term(self) -> Generator[tuple[str, tuple[int], float | complex], None, None]: ...
    def __radd__(self, oper: SpinOper | number) -> SpinOper: ...
    def __mul__(self, scale: SpinOper | number) -> SpinOper: ...
    def __rmul__(self, scale) -> SpinOper: ...
    def __sub__(self, oper: SpinOper | number) -> SpinOper: ...
    def __rsub__(self, oper: SpinOper | number) -> SpinOper: ...
    def __neg__(self) -> SpinOper: ...
    def __truediv__(self, num: float | complex) -> SpinOper: ...
    def __matmul__(self, oper: SpinOper) -> SpinOper: ...
    def __pow__(self, n, m: Incomplete | None = None) -> SpinOper: ...
    def show_string_form(self, maxlen=80, form:Literal["v", "h"]='v') -> None: ...
    def save(self, filename:str = 'ham.h5') -> None: ...
    @classmethod
    def load(cls, filename:str) -> 'SpinOper': ...
    def sort_posn(self) -> SpinOper: ...
    def expandxy(self, pauli: bool = False) -> SpinOper: ...
    def dtype(self) -> Type[Union[float, complex]]: ...
    def split_data(self) -> tuple[list[str], list[tuple[int]], list[int | float | complex]]: ...
    def quspin_form(self) -> list[list[list[int | float | complex]]]: ...
    @overload
    def to_matrix(self, basis, sparse: Literal[False] = False, pauli: bool = False) -> _np.ndarray: ...
    @overload
    def to_matrix(self, basis, sparse: Literal[True], pauli: bool = False) -> _sp.csr_array: ...
    def automata(self, L: int|None = None, pauli: bool = False, d: int = 2, local_matrix: Callable[[str], _np.ndarray] | None = None) -> list[_np.ndarray]: ...
    def gate2_decomposition(self, L:int, tau=0.1, form:Literal["ladder", "brick"]="ladder", pauli:bool=True) -> tuple[list[int],list[_np.ndarray]]: ...
    def trotter_gates(self, L:int, tau:float, order:Literal["1", "2", "4", "4_opt"]="2", evolve_type:Literal["time", "temporal"]="time", N_step:int=1, pauli:bool=True) -> tuple[list[int], list[_np.ndarray]]: ...
    def local(self, site_position:int, L:int|None=None, pauli:bool=True) -> _np.ndarray: ...
    @overload
    def to_mpo(self, L=None, pauli=False, backend: Literal["torch"]='torch', device:Optional[str]=None) -> tcMPO: ...
    @overload
    def to_mpo(self, L=None, pauli=False, backend: Literal["quimb"]='quimb', device:Optional[str]=None) -> quMPO: ...
    def energies(self, pauli=None) -> _np.ndarray: ...
    @overload
    def gdenergy(self, pauli=None, k=1, return_eigenvectors:Literal[True, False]=False) -> _np.ndarray: ...
    @overload
    def gdenergy(self, pauli=None, k=1, return_eigenvectors:Literal[True, False]=True) -> tuple[_np.ndarray, _np.ndarray]: ...
    def evolve(self, inistate, tlist, obslist, L=None, pauli=False): ...


class SpinOperBuilder:
    def __init__(self): ...
    def build(self) -> SpinOper: ...
    
    
def I(i: int = 0) -> SpinOper: ...
def p(i: int = 0) -> SpinOper: ...
def m(i: int = 0) -> SpinOper: ...
def x(i: int = 0) -> SpinOper: ...
def y(i: int = 0) -> SpinOper: ...
def z(i: int = 0) -> SpinOper: ...
def n(i: int = 0) -> SpinOper: ...
def nn(i: int, j: int) -> SpinOper: ...
def zz(i: int, j: int) -> SpinOper: ...
def mp(i: int, j: int) -> SpinOper: ...
def pm(i: int, j: int) -> SpinOper: ...
def xx(i: int, j: int) -> SpinOper: ...
def yy(i: int, j: int) -> SpinOper: ...
def xy(i: int, j: int) -> SpinOper: ...
def yx(i: int, j: int) -> SpinOper: ...
def sum(SpinOper) -> SpinOper: ...
def heisenberg_operator(L:int, j:Union[number, Iterable[number]] = 1.0, h:Union[number, Iterable[number]] = 0.0, cyclic: bool=False) -> HeisenbergOper: ...

class HeisenbergOper(SpinOper):
    def energies(self, isinf=False, pauli=False): ...
    def gdenergy(self, isinf=False, pauli=False): ...