# -*- coding: utf-8 -*-

# @Author: hzhu
# @Date:   2024-10-30 21:12:57
# @Last Modified by:   hzhu
# @Last Modified time: 2024-10-31 20:39:56

# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html


import os 
import sys
sys.path.insert(0, os.path.abspath('..'))

# -- General configuration ------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'nbsphinx',  # 添加 nbsphinx
    "sphinx.ext.mathjax",
    # "numpydoc",
    "sphinx.ext.autodoc",
    'sphinx.ext.doctest',
    "sphinx.ext.intersphinx",
    "sphinx.ext.coverage",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    #'sphinx.ext.autosectionlabel', # doesn't seem to work
    # "sphinxtogithub",
    "sphinx.ext.napoleon",
    # "sphinxcontrib.googleanalytics",
    # "sphinx_rtd_size", # allows to fix width of rtd sphinx theme
    'sphinx_prompt',
]


autodoc_default_options = {
    'undoc-members': True,          # 包括没有文档字符串的成员
    "members": True,  # 如果设置为 True，则会包括模块、类或函数的所有成员（方法和属性）；如果设置为 False，则不包括成员。
    "inherited-members": True,  # 如果设置为 True，则会包括从基类继承的成员。
    "show-inheritance": True,
    # "no-special-members": True,
    # "no-private-members": True,
    # "no-undoc-members": True,
    "member-order": 'bysource',
    # "undoc-members": True,
    "exclude-members": "__init__",
}

autosummary_generate = True  # Make _autosummary files and include them

# Only the class' docstring is inserted.
# autoclass_content = "class"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# remove duplicates
numpydoc_show_class_members = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

nbsphinx_execute = 'never'  # 禁止 Sphinx 执行 Jupyter Notebook 中的代码
nbsphinx_allow_errors = True  # 允许包含错误的 Notebook 继续生成

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'Quante'
copyright = '2024, Hao Zhu, Dingzu Wang'
author = 'Hao Zhu, Dingzu Wang'


# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# The full version, including alpha/beta/rc tags.
release = '0.1.0'


# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
# exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
# exclude_patterns = ['links.rst', 'README.rst']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output


## google analytics
# googleanalytics_id = 'UA-110543543-1' # old tag, deprecated since July 2023
# googleanalytics_id = "G-6885KZ7NH6"


html_theme = "sphinx_rtd_theme"
# html_theme_options = {
#     'analytics_id': googleanalytics_id,  #  Provided by Google in your dashboard
#     'analytics_anonymize_ip': False,
#     #'logo_only': True,
#     #'display_version': True,
#     #'prev_next_buttons_location': 'bottom',
#     'style_external_links': True,
#     'vcs_pageview_mode': '',
#     #'style_nav_header_background': 'blue',
#     # Toc options
#     'collapse_navigation': True,
#     'sticky_navigation': True,
#     'navigation_depth': 4,
#     'includehidden': True,
#     'titles_only': False
# }
sphinx_rtd_size_width = "100%"


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".


# These folders are copied to the documentation's HTML output
html_static_path = ['_static']

# These paths are either relative to html_static_path
# or fully qualified paths (eg. https://...)
html_css_files = [
    'css/py_class_property_fix.css',
    "css/custom.css"
]

html_theme_options = {
    'display_version': True,
    'body_max_width': 'auto',  # Adjusts body width on larger screens
}

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "Quantedoc"


